import { customerTypes } from './static.data';

export const CustomerForm = {
  title: 'Customers',
  tableName: 'customers',
  pk: 'customer_id',
  columns: [
    {
      fldName: 'customer_type',
      control: 'select',
      type: 'list',
      label: 'Customer type',
      listData: customerTypes,
      valueFld: 'id',
      displayFld: 'type',
      required: true,
      size: 4,
    },
    {
      fldName: 'customer_name',
      control: 'input',
      type: 'text',
      label: 'Customer Name',
      required: true,
      size: 8,
    },
    {
      fldName: 'cell_no',
      control: 'input',
      type: 'text',
      label: 'Cell No',
      required: true,
      size: 4,
    },
    {
      fldName: 'whatsapp_no',
      control: 'input',
      type: 'text',
      label: 'WhatsApp No',
      required: true,
      size: 4,
    },
    {
      fldName: 'email',
      control: 'input',
      type: 'email',
      label: 'Email',
      size: 4,
    },
    // {
    //   fldName: 'address',
    //   control: 'input',
    //   type: 'text',
    //   label: 'Address',
    //   size: 8,
    // },
    {
      fldName: 'nationality_id',
      control: 'select',
      type: 'lookup',
      label: 'Nationality',
      listTable: 'nationality',
      listData: [],
      valueFld: 'nationality_id',
      displayFld: 'nationality_name',
      required: true,
      size: 4,
    },
  ],
};

export const CashReciept_Form = {
  title: 'Cash Receipt',
  tableName: 'vouchers',
  pk: 'voucher_id',
  columns: [
    {
      fldName: 'date',
      control: 'input',
      type: 'date',
      label: 'Date',
      required: true,
      size: 4,
    },
    {
      fldName: 'invoice_id',
      control: 'input',
      type: 'text',
      label: 'Invoice No',
      readonly: true,
      size: 4,
    },
    {
      fldName: 'ref_no',
      control: 'input',
      type: 'text',
      label: 'Reference No',

      size: 4,
    },

    {
      fldName: 'payment_mode',
      control: 'select',
      type: 'lookup',
      label: 'Payment Mode',
      listTable: 'payment_modes',
      listData: [],
      valueFld: 'id',
      displayFld: 'payment_mode',
      size: 4,
    },

    {
      fldName: 'description',
      control: 'input',
      type: 'text',
      label: 'Description',
      required: true,
      size: 8,
    },

    {
      fldName: 'credit',
      control: 'input',
      type: 'number',
      label: 'Amount',
      size: 4,
      required: true,
    },
    {
      fldName: 'account_id',
      control: 'select',
      type: 'lookup',
      label: 'Select Account',
      listTable: 'qrycashaccts',
      listData: [],
      valueFld: 'account_id',
      displayFld: 'account_name',
      required: true,
      size: 4,
    },
    {
      fldName: 'customer_id',
      control: 'input',
      type: 'hidden',
      label: 'Customer',
      visible: false,
      size: 4,
    },
  ],
};
export const SupplierPayment_Form = {
  title: 'Cash Payment',
  tableName: 'vouchers',
  pk: 'voucher_id',
  columns: [
    {
      fldName: 'date',
      control: 'input',
      type: 'date',
      label: 'Date',
      required: true,
      size: 4,
    },
    {
      fldName: 'bill_id',
      control: 'input',
      type: 'text',
      label: 'Bill No',
      readonly: true,
      size: 4,
    },
    {
      fldName: 'ref_no',
      control: 'input',
      type: 'text',
      label: 'Reference No',
      size: 4,
    },

    {
      fldName: 'payment_mode',
      control: 'select',
      type: 'lookup',
      label: 'Payment Mode',
      listTable: 'payment_modes',
      listData: [],
      valueFld: 'id',
      displayFld: 'payment_mode',
      size: 4,
    },

    {
      fldName: 'description',
      control: 'input',
      type: 'text',
      label: 'Description',
      required: true,
      size: 8,
    },

    {
      fldName: 'debit',
      control: 'input',
      type: 'number',
      label: 'Amount',
      size: 4,
      required: true,
    },
    {
      fldName: 'account_id',
      control: 'select',
      type: 'lookup',
      label: 'Select Account',
      listTable: 'qrycashaccts',
      listData: [],
      valueFld: 'account_id',
      displayFld: 'account_name',
      required: true,
      size: 4,
    },
    {
      fldName: 'supplier_id',
      control: 'input',
      type: 'hidden',
      label: 'Customer',
      visible: false,
      size: 4,
    },
  ],
};
