import { statusData } from '../../../factories/static.data';
import { AddLookupFld } from '../../components/crud-form/crud-form-helper';

export const EmployeesInfo = {
  title: 'Employee Personel Info',
  tableName: 'users',
  pk: 'userid',
  columns: [
    {
      fldName: 'first_name',
      control: 'input',
      type: 'text',
      label: 'First Name',
      required: true,
      size: 6,
    },
    {
      fldName: 'last_name',
      control: 'input',
      type: 'text',
      label: 'Last Name',
      required: true,
      size: 6,
    },
    {
      fldName: 'designation_id',
      control: 'select',
      type: 'lookup',
      label: 'Designation',
      listTable: 'users_designation',
      listdata: [],
      displayFld: 'designation_name',
      valueFld: 'designation_id',
      required: true,
      size: 6,
    },
    {
      fldName: 'dept_id',
      control: 'select',
      type: 'list',
      label: 'Department',
      listTable: 'depts',
      listData: [],
      displayFld: 'dept_name',
      valueFld: 'dept_id',
      required: true,
      size: 6,
    },
    AddLookupFld(
      'supervisor',
      'Supervisor',
      'users',
      'userid',
      'first_name',
      6, null, false

    ),
    {
      fldName: 'salary_type',
      control: 'select',
      type: 'list',
      label: 'Salary Type',
      listTable: '',
      listData: [
        { id: 'Basic', value: 'Basic' },
        { id: 'Comm', value: 'Comm' },
      ],
      displayFld: 'value',
      valueFld: 'id',
      required: true,
      size: 6,
    },
    {
      fldName: 'monthly_salary',
      control: 'input',
      type: 'number',
      label: 'Monthly Salary',
      required: false,
      size: 6,
    },
    {
      fldName: 'allowance',
      control: 'input',
      type: 'number',
      label: 'Allowance',
      required: false,
      size: 6,
    },
    {
      fldName: 'email',
      control: 'input',
      type: 'text',
      label: 'E-Mail',
      required: false,
      size: 6,
    },
    {
      fldName: 'phone',
      control: 'input',
      type: 'text',
      label: 'Phone No',
      required: false,
      size: 6,
    },
    {
      fldName: 'gender',
      control: 'select',
      type: 'list',
      label: 'Gender',
      listTable: '',
      listData: [
        { id: 'Male', value: 'Male' },
        { id: 'Female', value: 'Female' },
      ],
      displayFld: 'value',
      valueFld: 'id',
      required: true,
      size: 6,
    },
    {
      fldName: 'dob',
      control: 'input',
      type: 'date',
      label: 'Date of Birth',
      required: false,
      size: 6,
    },
    {
      fldName: 'join_date',
      control: 'input',
      type: 'date',
      label: 'Date of Joining',
      required: true,
      size: 6,
    },
    {
      fldName: 'marital_status',
      control: 'select',
      type: 'list',
      label: 'Marital Statud',
      listTable: '',
      listData: [
        { id: 'Married', value: 'Married' },
        { id: 'Un-Married', value: 'Un-Married' },
      ],
      displayFld: 'value',
      valueFld: 'id',
      required: true,
      size: 6,
    },
    {
      fldName: 'education',
      control: 'input',
      type: 'text',
      label: 'Education',
      required: false,
      size: 6,
    },
    {
      fldName: 'document_attested',
      control: 'select',
      type: 'list',
      label: 'Document Attested',
      listTable: '',
      listData: [
        { id: 'Yes', value: 'Yes' },
        { id: 'No', value: 'No' },
      ],
      displayFld: 'value',
      valueFld: 'id',
      required: true,
      size: 6,
    },
    {
      fldName: 'group_id',
      control: 'select',
      type: 'list',
      label: 'Group',
      listTable: 'usergroups',
      listData: [],
      displayFld: 'group_name',
      valueFld: 'group_id',
      required: true,
      size: 6,
    },
    {
      fldName: 'active',
      control: 'select',
      type: 'list',
      label: 'Status',
      listTable: '',
      listData: statusData,
      displayFld: 'status',
      valueFld: 'id',
      required: true,
      size: 6,
    },

    {
      fldName: 'link',
      control: 'file',
      label: 'Document',
      size: 4,
    },
  ],
};
