import { RouteInfo } from './vertical-menu.metadata';

//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    id: 100,
    path: '/dashboard',
    title: 'Dashboard',
    icon: 'ft-home',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    group: [1, 2, 3],
  },

  {
    id: 200,
    path: '/sale/invoice',
    title: 'Tasks',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1,2],
    submenu: [
      {
        id: 210,
        path: '/sale/sales',
        title: 'Sugar Sale',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 210,
        path: '/sale/invoices',
        title: 'Trolla Sale',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 310,
        path: '/purchase/purchases',
        title: 'Sugar Purchase',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },

      {
        id: 350,
        path: '/purchase/booking',
        title: 'Trolla Purchase',
        icon: 'ft-shopping-bag submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 350,
        path: '/sale/orders-list',
        title: 'Sale Orders',
        icon: 'ft-shopping-bag submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2,3],
      },
      {
        id: 350,
        path: '/sale/transfer',
        title: 'Stock Transfer',
        icon: 'ft-shopping-bag submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },

      {
        id: 440,
        path: '/cash/journalvoucher',
        title: 'Cash Online',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 420,
        path: '/cash/cashreceipt',
        title: 'Cash Receipt',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 430,
        path: '/cash/cashpayment',
        title: 'Cash Payment',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },


    ],
  },
  {
    id: 800,
    path: '/reports',
    title: 'Reports',
    icon: 'ft-pie-chart',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1,2],
    submenu: [
      // {
      //   id: 805,
      //   path: '/reports/daybook',
      //   title: 'Day Book',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },
      {
        id: 810,
        path: '/reports/cashbook',
        title: 'Cash Book',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 815,
        path: '/reports/salereport',
        title: 'Sale Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 815,
        path: '/reports/ordersreport',
        title: 'Orders Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 820,
        path: '/reports/purchasereport',
        title: 'Purchase Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },

      // {
      //   id: 835,
      //   path: '/reports/labourreport',
      //   title: 'Labour Report',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },

      // {
      //   id: 845,
      //   path: '/reports/sale-ledger',
      //   title: 'Sale Ledger',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },
      // {
      //   id: 850,
      //   path: '/reports/purchase-ledger',
      //   title: 'Purchase Ledger',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },
      {
        id: 853,
        path: '/reports/purchase-bystore',
        title: 'Purchase By Store',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2,3],
      },
      // {
      //   id: 854,
      //   path: '/reports/stock-transfer',
      //   title: 'Transfer Report',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2,3],
      // },
      {
        id: 855,
        path: '/reports/stockreport',
        title: 'Stock Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2,3],
      },
      {
        id: 856,
        path: '/reports/stock-bydate',
        title: 'Stock Report - By Date',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2,3],
      },
      {
        id: 860,
        path: '/reports/stockaccts',
        title: 'Stock Account',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2,3],
      },
      // {
      //   id: 865,
      //   path: '/reports/salesummay',
      //   title: 'Sale of Products',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },
      // {
      //   id: 870,
      //   path: '/reports/purchasesummay',
      //   title: 'Purchase of Products',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },
      {
        id: 875,
        path: '/reports/creditlist',
        title: 'Credit List',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      // {
      //   id: 880,
      //   path: '/reports/expensereport',
      //   title: 'Expense Report',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },
      {
        id: 885,
        path: '/reports/balancesheet',
        title: 'Balance Sheet',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      // {
      //   id: 890,
      //   path: '/reports/profit',
      //   title: 'Profit Report',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },
      // {
      //   id: 895,
      //   path: '/reports/profitbybill',
      //   title: 'Profit By Bill',
      //   icon: 'ft-info submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },
    ],
  },
  {
    id: 500,
    path: '/accounts',
    title: 'Accounts',
    icon: 'ft-users',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1,2],
    submenu: [
      {
        id: 510,
        path: '/accounts/accounts',
        title: 'Accounts List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 520,
        path: '/accounts/accountledger',
        title: 'Account Ledger',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 530,
        path: '/accounts/accttypes',
        title: 'Account Types',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
    ],
  },
  {
    id: 600,
    path: '/products',
    title: 'Products',
    icon: 'ft-grid',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1,2],
    submenu: [
      {
        id: 610,
        path: '/products/products',
        title: 'Products',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 620,
        path: '/products/units',
        title: 'Product Units',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 620,
        path: '/products/categories',
        title: 'Product Categories',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
    ],
  },
  {
    id: 700,
    path: '/settings',
    title: 'Settings',
    icon: 'ft-settings',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1,2],
    submenu: [
      // {
      //   id: 710,
      //   path: '/settings/labourheads',
      //   title: 'Labour Heads',
      //   icon: 'ft-arrow-right submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },

      {
        id: 730,
        path: '/settings/stores',
        title: 'Manage Stores',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 730,
        path: '/settings/business',
        title: 'Business Details',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      {
        id: 750,
        path: '/settings/grouprights',
        title: 'Groups Rights',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
      // {
      //   id: 760,
      //   path: '/settings/expheads',
      //   title: 'Expense Heads',
      //   icon: 'ft-arrow-right submenu-icon',
      //   class: '',
      //   badge: '',
      //   badgeClass: '',
      //   isExternalLink: false,
      //   submenu: [],
      //   group: [1,2],
      // },
      {
        id: 770,
        path: '/settings/users',
        title: 'Users',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1,2],
      },
    ],
  },
];
