import { RouteInfo } from './vertical-menu.metadata';

//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    id: 100,
    path: '/dashboard',
    title: 'Dashboard',
    icon: 'ft-home',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    group: [1, 2, 3],
  },
  {
    id: 200,
    path: '/sale/invoice',
    title: 'Taks',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 210,
        path: '/sale/order/',
        title: 'Sale Order',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 215,
        path: '/sale/invoice/',
        title: 'Sale',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },

      {
        id: 220,
        path: '/purchase/invoice/',
        title: 'Purchase',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },

      {
        id: 225,
        path: '/sale/gold',
        title: 'Gold Transaction',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 230,
        path: '/sale/chandi',
        title: 'Chandi Transaction',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },

      {
        id: 240,
        path: '/sale/goldconvert',
        title: 'Gold Convert',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 250,
        path: '/sale/cash-receipt',
        title: 'Cash Receipt',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 260,
        path: '/sale/cash-paid',
        title: 'Cash Paid',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
{
        id: 270,
        path: '/sale/gold-paid-receipt',

        title: 'Gold Paid Receipt',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 270,
        path: '/sale/wages-paid',
        title: 'Wages Paid',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },

    ],
  },

  {
    id: 800,
    path: '/reports',
    title: 'Reports',
    icon: 'ft-pie-chart',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 805,
        path: '/reports/daybook',
        title: 'Day Book',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 810,
        path: '/reports/cashbook',
        title: 'Cash Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 830,
        path: '/reports/salereport',
        title: 'Sale Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 840,
        path: '/reports/purchasereport',
        title: 'Purchase Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },


      {
        id: 820,
        path: '/reports/polishreport',
        title: 'Polish Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 820,
        path: '/reports/labourreport',
        title: 'Labour Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },


 {
        id: 855,
        path: '/reports/stock-report',
        title: 'Stock Reports ',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        group: [1, 2, 3],
        submenu: [],
      },
       {
        id: 855,
        path: '/reports/stockaccts',
        title: 'Stock Accounts',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        group: [1, 2, 3],
        submenu: [],
      },

      {
        id: 835,
        path: '/reports/rawgoldreport24k',
        title: 'Raw Gold 24K Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 835,
        path: '/reports/rawgoldreport22k',
        title: 'Raw Gold 22/21K Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
{
        id: 850,
        path: '/reports/purchasesummary',
        title: 'Purchase Summary',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 835,
        path: '/reports/salesummary',
        title: 'Sale Summary',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },

      {
        id: 845,
        path: '/reports/purchase-ledger',
        title: 'Purchase Ledger',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },

    ],
  },

  {
    id: 500,
    path: '/accounts',
    title: 'Accounts',
    icon: 'ft-users',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 510,
        path: '/accounts/accounts',
        title: 'Accounts List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 520,
        path: '/accounts/accountledger',
        title: 'Account Ledger',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
  {
    id: 700,
    path: '/settings',
    title: 'Settings',
    icon: 'ft-settings',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 710,
        path: '/products/products',
        title: 'Products',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },

      {
        id: 750,
        path: '/settings/grouprights',
        title: 'Groups Rights',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 770,
        path: '/settings/users',
        title: 'Users',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
];
