import { RouteInfo } from './vertical-menu.metadata';

//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    id: 100,
    path: '/dashboard',
    title: 'Dashboard',
    icon: 'ft-home',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    group: [1, 2, 3],
  },
  {
    id: 200,
    path: '/sale/invoice',
    title: 'Taks',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 210,
        path: '/sale/order/',
        title: 'Sale Order',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 215,
        path: '/sale/invoice/',
        title: 'Sale',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },

      {
        id: 220,
        path: '/purchase/invoice/',
        title: 'Purchase',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },

      {
        id: 225,
        path: '/sale/gold',
        title: 'Gold Transaction',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 230,
        path: '/sale/chandi',
        title: 'Chandi Transaction',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },

      {
        id: 240,
        path: '/sale/goldconvert',
        title: 'Gold Convert',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 250,
        path: '/sale/cash-receipt',
        title: 'Cash Receipt',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 260,
        path: '/sale/cash-paid',
        title: 'Cash Paid',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },

      {
        id: 270,
        path: '/sale/wages-paid',
        title: 'Wages Paid',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 280,
        path: '/sale/advance-receipt',

        title: 'Adavnce Receipt',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 270,
        path: '/sale/advance-paid',
        title: 'Advance Paid',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },

  {
    id: 800,
    path: '/reports',
    title: 'Reports',
    icon: 'ft-pie-chart',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 805,
        path: '/reports/daybook',
        title: 'Day Book',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 810,
        path: '/reports/cashbook',
        title: 'Cash Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 811,
        path: '/reports/vouchers',
        title: 'Vouchers Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 845,
        path: '/reports/labourreport',
        title: 'Labour Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 814,
        path: '/reports/salereport',
        title: 'Sale Reports',
        icon: 'ft-pie-chart',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        group: [1, 2],
        submenu: [
          {
            id: 815,
            path: '/reports/salereport',
            title: 'Sale Report',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
          {
            id: 818,
            path: '/reports/sale-orders',
            title: 'Sale Order Report (Pending)',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
          {
            id: 865,
            path: '/reports/salesummay',
            title: 'Sale Summary',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
          {
            id: 866,
            path: '/reports/sale-ledger',
            title: 'Sale Ledger',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2, 3],
          },
          {
            id: 868,
            path: '/reports/farmer-sale',
            title: 'Farmer Sale Report',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2, 3],
          },
          {
            id: 870,
            path: '/reports/farmer-list',
            title: 'Farmer List',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2, 3],
          },
          {
            id: 880,
            path: '/reports/sale-analysis',
            title: 'Sale Analysis',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
          {
            id: 890,
            path: '/reports/product-sale',
            title: 'Sale of Products',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
        ],
      },
      {
        id: 820,
        path: '/reports',
        title: 'Purchase Reports',
        icon: 'ft-pie-chart',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        group: [1, 2],
        submenu: [
          {
            id: 821,
            path: '/reports/purchasereport',
            title: 'Purchase Report',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
          {
            id: 825,
            path: '/reports/purchase-orders',
            title: 'Purchase Orders (Pending)',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
          {
            id: 871,
            path: '/reports/purchase-ldger',
            title: 'Purchase Ledger',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2, 3],
          },
          {
            id: 892,
            path: '/reports/product-purchase',
            title: 'Purchase of Products',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
        ],
      },
      {
        id: 822,
        path: '/reports',
        title: 'Purchase Reports',
        icon: 'ft-pie-chart',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        group: [1, 2],
        submenu: [],
      },

      {
        id: 840,
        path: '/reports/stock-report',
        title: 'Stock Reports ',
        icon: 'ft-pie-chart',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        group: [1, 2, 3],
        submenu: [],
      },
      {
        id: 870,
        path: '/reports/stock-report',
        title: 'Stock Report',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 872,
        path: '/reports/stock-edit',
        title: 'Stock Edit',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 875,
        path: '/reports/stock-bydate',
        title: 'Stock Report - By Date',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 878,
        path: '/reports/stockaccts',
        title: 'Stock Account',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 882,
        path: '/reports/short-stock',
        title: 'Short Stock',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
  {
    id: 841,
    path: '/reports/stock-report',
    title: 'DMA & WHTReport ',
    icon: 'ft-pie-chart',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2, 3],
    submenu: [
      {
        id: 885,
        path: '/reports/dma-vouchers',
        title: 'DMA Voucher Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 830,
        path: '/reports/dmareport',
        title: 'DMA Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 885,
        path: '/reports/wht-report',
        title: 'WHT Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 888,
        path: '/reports/wht-by-payment',
        title: 'WHT By Payment',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 840,
        path: '/reports/stock-report',
        title: 'Analysis Report ',
        icon: 'ft-pie-chart',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        group: [1, 2, 3],
        submenu: [
          {
            id: 855,
            path: '/reports/observations',
            title: 'Observation Report',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
          {
            id: 860,
            path: '/reports/no-business',
            title: 'No Business Report',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
        ],
      },
      {
        id: 840,
        path: '/reports/daily-profit',
        title: 'Profit Reports ',
        icon: 'ft-pie-chart',
        class: 'has-sub',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        group: [1, 2],
        submenu: [
          {
            id: 835,
            path: '/reports/daily-profit',
            title: 'Daily Profit ',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2, 3],
          },
          {
            id: 836,
            path: '/reports/profit-summary',
            title: 'Profit Summar ',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2, 3],
          },
          {
            id: 885,
            path: '/reports/balancesheet',
            title: 'Balance Sheet',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
          {
            id: 850,
            path: '/reports/trialbalance',
            title: 'Trail Balance',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
          {
            id: 860,
            path: '/reports/diary-report',
            title: 'Dairy Report',
            icon: 'ft-info submenu-icon',
            class: '',
            badge: '',
            badgeClass: '',
            isExternalLink: false,
            submenu: [],
            group: [1, 2],
          },
        ],
      },
    ],
  },
  {
    id: 500,
    path: '/accounts',
    title: 'Accounts',
    icon: 'ft-users',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 510,
        path: '/accounts/accounts',
        title: 'Accounts List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 520,
        path: '/accounts/accountledger',
        title: 'Account Ledger',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
  {
    id: 700,
    path: '/settings',
    title: 'Settings',
    icon: 'ft-settings',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 710,
        path: '/products/products',
        title: 'Products',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 710,
        path: '/settings/ctrlaccts',
        title: 'Control Accounts',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },

      {
        id: 750,
        path: '/settings/grouprights',
        title: 'Groups Rights',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 770,
        path: '/settings/users',
        title: 'Users',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
];
