import { RouteInfo } from './vertical-menu.metadata';

// Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    id: 1000,
    path: '/dashboard',
    title: 'Dashboard',
    icon: 'tachometer',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    group: [1, 2],
  },
  {
    id: 2000,
    path: '',
    title: 'Sales/Purchase',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        id: 2010,
        path: '/sale/sale',
        title: 'Sale',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 2020,
        path: '/purchase/purchase',
        title: 'Purchase',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
    ],
    group: [1, 2, 3],
  },
  {
    id: 3000,
    path: '',
    title: 'Payment',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        id: 3010,
        path: '/cash/cashreceipt',
        title: 'Amount Receipt',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 3020,
        path: '/cash/cashpayment',
        title: 'Amount Payment',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 3030,
        path: '/cash/expense',
        title: 'Add Expense',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 3040,
        path: '/cash/transfer',
        title: 'Cash Transfer',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
    group: [1, 2],
  },
  {
    id: 4000,
    path: '',
    title: 'Reports',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        id: 4010,
        path: '/reports/daybook',
        title: 'Day Book',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4020,
        path: '/reports/cashreport',
        title: 'Cash Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4030,
        path: '/reports/purchasereport',
        title: 'Purchase Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1],
      },
      {
        id: 4040,
        path: '/reports/salereport',
        title: 'Sale Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4050,
        path: '/reports/currentbalance',
        title: 'Current Balance',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4060,
        path: '/reports/nobusiness',
        title: 'No Business Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4070,
        path: '/reports/creditreport',
        title: 'Credit List',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4080,
        path: '/reports/stockreport',
        title: 'Stock Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4090,
        path: '/reports/stocksm',
        title: 'Stock Salesman',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 4100,
        path: '/reports/stockaccts',
        title: 'Stock Accounts',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4110,
        path: '/reports/expensereport',
        title: 'Expense Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4120,
        path: '/reports/balancesheet',
        title: 'Balance Sheet',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 4130,
        path: '/reports/profit',
        title: 'Profit Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1],
      },
    ],
    group: [1, 2, 3],
  },
  {
    id: 5000,
    path: '',
    title: 'Accounts',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 5010,
        path: '/customers/customers',
        title: 'Customers',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 5020,
        path: '/customers/customeraccts',
        title: 'Customers Ledger',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
  {
    id: 6000,
    path: '',
    title: 'Setup',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        id: 6010,
        path: '/settings/products',
        title: 'Products',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 6020,
        path: '/settings/companies',
        title: 'Companies',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 6030,
        path: '/settings/expensheads',
        title: 'Expense Heads',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 6040,
        path: '/settings/users',
        title: 'Users',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1],
      },
    ],
    group: [1, 2],
  },
];

