import { RouteInfo } from './vertical-menu.metadata';

//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    id: 100,
    path: '/dashboard',
    title: 'Dashboard',
    icon: 'ft-home',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    group: [1, 2, 3],
  },
  {
    id: 200,
    path: '/transport/invoice',
    title: 'Cement',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 210,
        path: '/purchase/booking',
        title: 'Booking',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 210,
        path: '/purchase/orders',
        title: 'Orders',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 220,
        path: '/cash/cashreceipt',
        title: 'Cash Receipt',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 230,
        path: '/cash/cashpayment',
        title: 'Cash Payment',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 240,
        path: '/cash/journalvoucher',
        title: 'Cash Tarnasfer',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 250,
        path: '/cash/expense',
        title: 'Add Expense',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
  {
    id: 300,
    path: '/transport/transport',
    title: 'Transport',
    icon: 'ft-shopping-cart',
    class: 'dropdown nav-item has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 310,
        path: '/transport/transport',
        title: 'Transport Accounts',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 320,
        path: '/transport/income',
        title: 'Income',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 330,
        path: '/transport/expense',
        title: 'Expense',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 340,
        path: '/transport/report',
        title: 'Profit/Loss Report',
        icon: 'ft-dollar-sign submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
  {
    id: 400,
    path: '/reports',
    title: 'Reports',
    icon: 'ft-pie-chart',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 410,
        path: '/reports/daybook',
        title: 'Day Book',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 420,
        path: '/reports/cashbook',
        title: 'Cash Book',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 430,
        path: '/reports/booking',
        title: 'Booking Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 480,
        path: '/reports/sale-ledger',
        title: 'Sale Ledger',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 490,
        path: '/reports/purchase-ledger',
        title: 'Purchase Ledger',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },

      {
        id: 530,
        path: '/reports/stockaccts',
        title: 'Stock Account',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2, 3],
      },
      {
        id: 540,
        path: '/reports/salesummay',
        title: 'Sale of Products',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 550,
        path: '/reports/purchasesummay',
        title: 'Purchase of Products',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 560,
        path: '/reports/creditlist',
        title: 'Credit List',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 570,
        path: '/reports/expensereport',
        title: 'Expense Report',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 580,
        path: '/reports/balancesheet',
        title: 'Balance Sheet',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 590,
        path: '/reports/profitbybill',
        title: 'Profit By Bill',
        icon: 'ft-info submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
  {
    id: 500,
    path: '/accounts',
    title: 'Accounts',
    icon: 'ft-users',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 510,
        path: '/accounts/accounts',
        title: 'Accounts List',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 520,
        path: '/accounts/accountledger',
        title: 'Account Ledger',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 530,
        path: '/accounts/accttypes',
        title: 'Account Types',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
  {
    id: 600,
    path: '/products',
    title: 'Products',
    icon: 'ft-grid',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 610,
        path: '/products/products',
        title: 'Products',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 630,
        path: '/products/categories',
        title: 'Product Categories',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
  {
    id: 700,
    path: '/settings',
    title: 'Settings',
    icon: 'ft-settings',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    group: [1, 2],
    submenu: [
      {
        id: 710,
        path: '/settings/grouprights',
        title: 'Groups Rights',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 720,
        path: '/settings/expheads',
        title: 'Expense Heads',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
      {
        id: 730,
        path: '/settings/users',
        title: 'Users',
        icon: 'ft-arrow-right submenu-icon',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        group: [1, 2],
      },
    ],
  },
];
