import {
  AddFormButton,
  AddSpace,
} from '../../../../../../../libs/future-tech-lib/src/lib/components/crud-form/crud-form-helper';
import { GoldTypes, TrType } from '../../../factories/static.data';

export const GolTrForm = {
  title: 'Gold Transaction',
  tableName: 'Cash',
  pk: 'CashID',
  columns: [
    {
      fldName: 'Date',
      control: 'input',
      type: 'date',
      label: 'Date',
      required: true,
      size: 2,
    },
    {
      fldName: 'TrType',
      control: 'select',
      type: 'list',
      label: 'Type',
      listTable: '',
      listData: TrType,
      displayFld: 'Type',
      valueFld: 'ID',
      required: true,
      size: 2,
    },
    {
      fldName: 'CustomerID',
      control: 'select',
      type: 'ngselect',
      label: 'Customer Name',
      listTable: 'Customers',
      listData: [],
      displayFld: 'CustomerName',
      valueFld: 'CustomerID',
      required: true,
      size: 5,
    },

    {
      fldName: 'CBal',
      control: 'input',
      type: 'text',
      label: 'C/Bal',
      readonly: true,
      size: 1,
    },
    {
      fldName: 'K24',
      control: 'input',
      type: 'text',
      label: '24K',
      readonly: true,
      size: 1,
    },
    {
      fldName: 'K22',
      control: 'input',
      type: 'text',
      label: '22/21K',
      readonly: true,
      size: 1,
    },
    {
      fldName: 'RawGold',
      control: 'input',
      type: 'number',
      label: 'Raw Gold (Gms)',
      size: 2,
    },
    {
      fldName: 'GoldTypeID',
      control: 'select',
      type: 'list',
      label: 'Gold Type',
      listTable: '',
      listData: GoldTypes,
      displayFld: 'GoldType',
      valueFld: 'ID',
      required: true,
      size: 2,
    },
    {
      fldName: 'GoldCutting',
      control: 'input',
      type: 'number',
      label: 'Gold Cutting (Gms)',
      size: 2,
    },
    {
      fldName: 'Gold',
      control: 'input',
      type: 'number',
      label: 'Total Gold (Gms)',
      readonly: true,
      size: 2,
    },
    {
      fldName: 'GoldRate',
      control: 'input',
      type: 'number',
      label: 'Gold Rate',
      required: true,
      size: 2,
    },
    {
      fldName: 'GoldAmount',
      control: 'input',
      type: 'number',
      label: 'Gold Amount',
      required: true,
      size: 2,
    },
    {
      fldName: 'Cash',
      control: 'input',
      type: 'number',
      label: 'Cash Amount',
      required: true,
      size: 2,
    },

    {
      fldName: 'TotalCash',
      control: 'input',
      type: 'number',
      label: 'Total Amount',
      required: true,
      size: 2,
    },
    {
      fldName: 'CashReceived',
      control: 'input',
      type: 'number',
      label: 'Cash Received',
      required: true,
      size: 2,
    },
    {
      fldName: 'CashBalance',
      control: 'input',
      type: 'number',
      label: 'Cash Balance',
      required: true,
      size: 2,
      readonly: true,
    },


    {
      fldName: 'Notes',
      control: 'textarea',
      type: 'text',
      label: 'Notes',
      size: 12,
    },
    AddFormButton('First', null, 1, 'fast-backward', 'primary'),
    AddFormButton('Prev', null, 1, 'backward', 'primary'),
    AddFormButton('Next', null, 1, 'fast-forward', 'primary'),
    AddFormButton('Last', null, 1, 'step-forward', 'primary'),
    AddSpace(4),
    AddFormButton('New', null, 1, 'file', 'primary'),
    AddFormButton('Save', null, 1, 'save', 'success'),
    AddFormButton('Cancel', null, 1, 'refresh', 'warning'),
  ],
};
