import { Menu } from './menu.model';
export const verticalMenuItems = [
    new Menu(1, 'Dashboard', 'dashboard', null, 'tachometer', null, false, 0, [1, 2]),
    new Menu(200, 'Sales', null, null, 'cart-plus', null, true, 0, [1, 2, 3]),
    new Menu(201, 'Sale', 'sale/sale', null, 'cart-plus', null, false, 200, [1, 2, 3]),
    new Menu(202, 'Sale Return', 'sale/salereturn', null, 'cart-plus', null, false, 200, [1, 2]),
    //  new Menu(205, 'Quotation', 'sale/quotation', null, 'cart-plus', null, false, 200, [1, 2]),
    // new Menu(203, 'Order', 'sale/order', null, 'cart-plus', null, false, 200, [1, 2, 3]),
    // new Menu(204, 'Orders List', 'sale/orderslist', null, 'cart-plus', null, false, 200, [1, 2, 3]),
    // // new Menu(203, 'Sale Order', 'sale/saleorder', null, 'cart-plus', null, false, 200, [1]),
    new Menu(300, 'Purchase', null, null, 'shopping-cart', null, true, 0, [1]),
    new Menu(302, 'Purchase', 'purchase/purchase', null, 'plus-square', null, false, 300, [1]),
    new Menu(303, 'Purchase Return', 'purchase/purchasereturn', null, 'plus-square-o', null, false, 300, [1]),
    new Menu(400, 'Payment', null, null, 'shopping-cart', null, true, 0, [1]),
   // new Menu(410, 'Recovery by SM', 'cash/recovery', null, 'plus-square', null, false, 400, [1, 2, 3]),
    new Menu(420, 'Amount Receipt', 'cash/cashreceipt', null, 'plus-square', null, false, 400, [1, 2]),
    new Menu(430, 'Amount Payment', 'cash/cashpayment', null, 'plus-square', null, false, 400, [1, 2]),
    new Menu(440, 'Payment- General Voucher', 'cash/journalvoucher', null, 'plus-square', null, false, 400, [1]),
    new Menu(450, 'Add Expense', 'cash/expense', null, 'plus-square', null, false, 400, [1, 2, 3]),

    new Menu(500, 'Reports', null, null, 'files-o', null, true, 0, [1, 2, 3]),
    new Menu(505, 'Day Book', 'reports/daybook', null, 'file-text', null, false, 500, [1, 2]),
    new Menu(515, 'Purchase Report', 'reports/purchasereport', null, 'file-text', null, false, 500, [1]),
    new Menu(520, 'Sale Report', 'reports/salereport', null, 'file-text', null, false, 500, [1, 2]),
    // new Menu(521, 'Quotation Report', 'reports/quotationreport', null, 'cart-plus', null, false, 500, [1, 2, 3]),
    // new Menu(525, 'Frenchiser Report', 'reports/frenchiser', null, 'file-text', null, false, 500, [1, 2]),
    new Menu(530, 'Credit List', 'reports/creditreport', null, 'file-text', null, false, 500, [1, 2]),

    // new Menu(540, 'Sale Summary', 'reports/salesumry', null, 'file-text', null, false, 500, [1, 2]),
    // new Menu(545, 'Order Report', 'sale/orderslist', null, 'file-text', null, false, 500, [1, 2]),
    new Menu(550, 'Stock Report', 'reports/stockreport', null, 'cart-plus', null, false, 500, [1, 2]),
    new Menu(556, 'Stock Accounts', 'reports/stockaccts', null, 'cart-plus', null, false, 500, [1, 2]),
    new Menu(560, 'Expense Report', 'reports/expensereport', null, 'cart-plus', null, false, 500, [1, 2, 3]),

    // new Menu(535, 'Vouchers List', 'reports/voucherlist', null, 'file-text', null, false, 500, [1, 2]),
    // new Menu(540, 'Cash Book', 'reports/cashbook', null, 'file-text', null, false, 500, [1, 2]),

    new Menu(551, 'Balance Sheet', 'reports/balancesheet', null, 'file-text', null, false, 500, [1]),
    new Menu(555, 'Profit Report', 'reports/profit', null, 'file-text', null, false, 500, [1]),
   // new Menu(557, 'Tax Report', 'reports/taxreport', null, 'file-text', null, false, 500, [1]),
    new Menu(100, 'Accounts', null, null, 'product-hunt', null, true, 0, [1, 2]),
    new Menu(101, 'Accounts List', 'customers', null, 'plus-circle', null, false, 100, [1, 2]),
    new Menu(102, 'Account Ledger', 'customers/customeraccts', null, 'plus-circle', null, false, 100, [1, 2]),
    new Menu(50, 'Setup', null, null, 'dot-circle-o', null, true, 0, [1, 2]),
    new Menu(51, 'Poducts', 'settings/products', null, 'plus-circle', null, false, 50, [1, 2]),
    new Menu(52, 'Companies', 'settings/companies', null, 'plus-circle', null, false, 50, [1]),
//    new Menu(53, 'Categories', 'settings/categories', null, 'plus-circle', null, false, 50, [1]),
    new Menu(54, 'Users', 'users', null, 'plus-circle', null, false, 50, [1, 2]),
    new Menu(55, 'Account Types', 'settings/salesman', null, 'plus-circle', null, false, 50, [1]),
    new Menu(56, 'Expense Heads', 'settings/expensheads', null, 'plus-circle', null, false, 50, [1]),
    //new Menu(57, 'Setups', 'settings/setups', null, 'plus-circle', null, false, 50, [1]),
    //  new Menu(58, 'Units', 'settings/units', null, 'plus-circle', null, false, 50, [1]),
];
export const horizontalMenuItems = verticalMenuItems;
