import { RouteInfo } from './vertical-menu.metadata';

//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    path: '/dashboard',
    title: 'Dashboard',
    icon: 'ft-home',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [2.5],
  },
  {
    path: 'patient/finddr',
    title: 'Find A Doctor',
    icon: 'ft-user',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [0],
  },
  {
    path: '/patient/appointments',
    title: 'Appointments',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [0],
  },
  {
    path: '/doctor/newappts',
    title: 'Appointments',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [5],
  },
  {
    path: '/doctor/today',
    title: 'Today Patients',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [2],
  },
  {
    path: '/doctor/previous-record',
    title: 'Previous Record',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [2],
  },
  {
    path: '/doctor/lab-bill',
    title: 'Lab Bill',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [5],
  },
  {
    path: '/doctor/cash-report',
    title: 'Cash Report',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [2, 5],
  },
  {
    path: '/doctor/lab-report',
    title: 'Lab Report',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [2, 4, 5],
  },
  {
    path: '/lab/booking-report',
    title: 'Bookings',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [4],
  },
  {
    path: '/lab/make-report',
    title: 'Make Report',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [4],
  },
  {
    path: '/lab/previous-reports',
    title: 'Previouse Reports',
    icon: 'ft-dollar-sign',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    Rights: [4],
  },
  {
    path: '',
    title: 'Management',
    icon: 'ft-dollar-sign',
    class: 'has-submenu',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    Rights: [2],
    submenu: [
      {
        path: '/lab/tests',
        title: 'Lab Test',
        icon: 'ft-dollar-sign',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        Rights: [2],
      },
      {
        path: '/lab/profiles',
        title: 'Test Profiles',
        icon: 'ft-dollar-sign',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        Rights: [2],
      },
      {
        path: '/lab/obs',
        title: 'Invetigations',
        icon: 'ft-dollar-sign',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        Rights: [2],
      },
      {
        path: '/lab/templates',
        title: 'Report Templates',
        icon: 'ft-dollar-sign',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        Rights: [2],
      },
    ],
  },
];
