export const ProductsForm = {
  title: 'Products List',
  tableName: 'Products',
  pk: 'ProductID',
  columns: [
    {
      fldName: 'Category',
      control: 'select',
      type: 'lookup',
      label: 'Category',
      listTable: 'Categories',
      listData: [],
      displayFld: 'CatName',
      valueFld: 'CatID',
      required: true,
      size: 4,
    },


    {
      fldName: 'ProductName',
      control: 'input',
      type: 'text',
      label: 'Proiduct Name',
      required: true,
      size: 12,
    },
    {
      fldName: 'Packing',
      control: 'input',
      type: 'number',
      label: 'Packing',
      required: true,
      size: 3,
    },
    {
      fldName: 'PackingWeight',
      control: 'input',
      type: 'number',
      label: 'Packing Weight',
      required: true,
      size: 3,
    },
    {
      fldName: 'SPrice',
      control: 'input',
      type: 'number',
      label: 'Sale Price',
      required: false,
      size: 3,
    },

    {
      fldName: 'UnitID',
      control: 'select',
      type: 'list',
      label: 'Unit',
      listTable: 'Units',
      listData: [],
      displayFld: 'UnitName',
      valueFld: 'ID',
      required: true,
      size: 3,
    },
    {
      fldName: 'PackingID',
      control: 'select',
      type: 'lookup',
      label: 'Packing 1',
      listTable: 'qryMasterPacking?orderby=ProductName',
      listData: [],
      displayFld: 'ProductName',
      valueFld: 'ProductID',
      required: true,
      size: 6,
    },
    {
      fldName: 'PackingID2',
      control: 'select',
      type: 'lookup',
      label: 'Packing 2',
      listTable: 'qryMasterPacking?orderby=ProductName',
      listData: [],
      displayFld: 'ProductName',
      valueFld: 'ProductID',
      required: false,
      size: 6,
    },
    {
      fldName: 'PackingID3',
      control: 'select',
      type: 'lookup',
      label: 'Packing 3',
      listTable: 'qryMasterPacking?orderby=ProductName',
      listData: [],
      displayFld: 'ProductName',
      valueFld: 'ProductID',
      required: false,
      size: 6,
    },
    {
      fldName: 'DivisionID',
      control: 'select',
      type: 'list',
      label: 'Division',
      listTable: 'Divisions',

      displayFld: 'DivisionName',
      valueFld: 'DivisionID',
      required: true,
      size: 3,
    },
    {
      fldName: 'PackSize',
      control: 'input',
      type: 'number',
      label: 'PackSize',
      required: true,
      size: 3,
    },
    {
      fldName: 'DrapStatus',
      control: 'select',
      type: 'list',
      label: 'Drap Status',
      listTable: 'DrapStatus',
      displayFld: 'Status',
      valueFld: 'ID',
      required: false,
      size: 3,
    },
    {
      fldName: 'DedStatus',
      control: 'select',
      type: 'list',
      label: 'Dedication',
      listTable: 'DedStatus',
      displayFld: 'DedStatus',
      valueFld: 'ID',
      required: false,
      size: 3,
    },
    {
      fldName: 'Form7No',
      control: 'input',
      type: 'text',
      label: 'Form 7',
      required: false,
      size: 3,
    },
    {
      fldName: 'MinimumStock',
      control: 'input',
      type: 'number',
      label: 'Minimum Stock',
      required: false,
      size: 3,
    },
    {
      fldName: 'Overheads',
      control: 'input',
      type: 'number',
      label: 'Overheads',
      required: false,
      size: 3,
    },
    {
      fldName: 'BusinessID',
      control: 'select',
      type: 'lookup',
      label: 'Business',
      listTable: 'Business',
      displayFld: 'BusinessName',
      valueFld: 'BusinessID',
      required: false,
      size: 5,
    },

    {
      fldName: 'Status',
      control: 'select',
      type: 'list',
      label: 'Status',
      listTable: '',
      listData: [
        {
          ID: 1,
          Status: 'Active',
        },
        {
          ID: 2,
          Status: 'In-Active',
        },
      ],
      displayFld: 'Status',
      valueFld: 'ID',
      required: true,
      size: 4,
    },
  ],
};

export const ProductsList = {
  tableName: 'qryproducts',
  pk: 'ProductID',
  columns: [
    { data: 'ProductID', label: 'ID' },
    { data: 'ProductName', label: 'Product Name' },
    { data: 'Packing', label: 'Packing' },
    { data: 'UnitName', label: 'Unit' },
    { data: 'Form7No', label: 'Form 7' },

    { data: 'SPrice', label: 'Sale Price' },
    { data: 'Status', label: 'Status' },
  ],
  actions: [
    { action: 'edit', title: 'Edit', icon: 'pencil', class: 'primary' },
    { action: 'delete', title: 'Delete', icon: 'trash', class: 'danger' },
  ],
};
