import { Status } from "../../../factories/constants";

export const AccountsForm = {
  title: 'Customers',
  tableName: 'Customers',
  pk: 'CustomerID',
  columns: [
    {
      fldName: 'AcctTypeID',
      control: 'select',
      type: 'list',
      label: 'Acct Type',
      listTable: 'AcctTypes',
      listData: [],
      displayFld: 'AcctType',
      valueFld: 'AcctTypeID',
      required: true,
      size: 6,
    },
    {
      fldName: 'AcctCatID',
      control: 'select',
      type: 'lookup',
      label: 'Acct Cat',
      listTable: 'AccountCat',
      listData: [],
      displayFld: 'CATEGORY',
      valueFld: 'CATID',
      required: true,
      size: 6,
    },
    {
      fldName: 'AcctID',
      control: 'select',
      type: 'lookup',
      label: 'Chat of Account',
      listTable: 'AccountChart',
      listData: [],
      displayFld: 'DESCRIPTION',
      valueFld: 'CODE',
      required: true,
      size: 6,
    },
    {
      fldName: 'ShortName',
      control: 'input',
      type: 'text',
      label: 'Short Name',

      size: 6,
    },
    {
      fldName: 'CustomerName',
      control: 'input',
      type: 'text',
      label: 'Account Name',
      required: true,
      size: 12,
    },
    {
      fldName: 'Address',
      control: 'input',
      type: 'text',
      label: 'Address',
      size: 6,
    },
    {
      fldName: 'City',
      control: 'select',
      type: 'dropdown',
      label: 'City',
      listTable: 'qryCities',
      listData: [],
      displayFld: 'City',
      valueFld: 'City',
      size: 4,
    },
    {
      fldName: 'PhoneNo1',
      control: 'input',
      type: 'text',
      label: 'Phone No 1',
      size: 6,
    },
    {
      fldName: 'PhoneNo2',
      control: 'input',
      type: 'text',
      label: 'Phone No 2',
      size: 6,
    },
    {
      fldName: 'Mobile',
      control: 'input',
      type: 'text',
      label: 'Mobile No',
      size: 6,
    },
    {
      fldName: 'Fax',
      control: 'input',
      type: 'text',
      label: 'Fax No',
      size: 6,
    },
    {
      fldName: 'SMSPhone',
      control: 'input',
      type: 'text',
      label: 'SMS Phone',
      size: 6,
    },
    {
      fldName: 'Email',
      control: 'input',
      type: 'email',
      label: 'Email',
      size: 6,
    },
    {
      fldName: 'Proprietor',
      control: 'input',
      type: 'text',
      label: 'Proprietor',
      size: 6,
    },

    {
      fldName: 'Gaurator',
      control: 'input',
      type: 'text',
      label: 'Gaurator',
      size: 6,
    },
    {
      fldName: 'ContactPerson',
      control: 'input',
      type: 'text',
      label: 'Contact Person',
      size: 6,
    },
    {
      fldName: 'Limit',
      control: 'input',
      type: 'number',
      label: 'Credit Limit',
      size: 6,
    },
    {
      fldName: 'RegisterPage',
      control: 'input',
      type: 'text',
      label: 'Register Page#',
      size: 6,
    },
    {
      fldName: 'RegistrationDate',
      control: 'input',
      type: 'date',
      label: 'Registration Date',
      size: 6,
    },
    {
      fldName: 'PartyCode',
      control: 'input',
      type: 'text',
      label: 'Party Code',
      size: 6,
    },
    {
      fldName: 'KissanCard',
      control: 'input',
      type: 'text',
      label: 'Kissan Card',
      size: 6,
    },

    {
      fldName: 'NTNNo',
      control: 'input',
      type: 'text',
      label: 'NTN/CNIC',
      size: 6,
    },
    {
      fldName: 'STN',
      control: 'input',
      type: 'text',
      label: 'STN No',
      size: 6,
    },
    {
      fldName: 'GroupID',
      control: 'select',
      type: 'lookup',
      label: 'Group',
      listTable: 'Groups',
      listData: '',
      displayFld: 'GroupName',
      valueFld: 'GroupID',
      required: true,
      size: 6,
    },
    {
      fldName: 'Status',
      control: 'select',
      type: 'list',
      label: 'Status',
      listTable: '',
      listData: Status,
      displayFld: 'Status',
      valueFld: 'ID',
      required: true,
      size: 6,
    },
    {
      fldName: 'Notes',
      control: 'textarea',
      type: 'text',
      label: 'Notes',
      size: 12,
    },

  ],
};
